
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
experimental:
  interface-name: en0

proxies:
  - {name: sghe.tjvpn.org, server: sghe.tjvpn.org, port: 443, udp: true, type: trojan, password: ceb4b440-b48f-11ec-b636-225401db9d57, sni: v27.tiktokcdn.com, skip-cert-verify: true}

proxy-groups:
  - name: sshkit-generator
    type: select
    proxies:
      - sghe.tjvpn.org

rules:
 - MATCH,sshkit-generator
