
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
unified-delay: true
ipv6: false
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  
proxies:
  - name: v27.tiktokcdn.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: v27.tiktokcdn.com
    skip-cert-verify: true
  - name: investor.medallia.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: investor.medallia.com
    skip-cert-verify: true
  - name: investor.spotify.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: investor.spotify.com
    skip-cert-verify: true
  - name: api2-t3.musical.ly
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: api2-t3.musical.ly
    skip-cert-verify: true
  - name: api-t3.tiktokv.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: api-t3.tiktokv.com
    skip-cert-verify: true
  - name: video.joox.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: video.joox.com
    skip-cert-verify: true
  - name: www.spotify.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: www.spotify.com
    skip-cert-verify: true
  - name: tiktokcdn.com.c.worldfcdn.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: tiktokcdn.com.c.worldfcdn.com
    skip-cert-verify: true
  - name: tiktokv.com.c.worldfcdn2.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: tiktokv.com.c.worldfcdn2.com
    skip-cert-verify: true
  - name: ttlivecdn.com.c.worldfcdn.com
    type: trojan
    server: sghe.tjvpn.org
    port: 443
    password: 97cc0ba0-e662-11ec-b235-225401db9d57
    udp: true
    sni: ttlivecdn.com.c.worldfcdn.com
    skip-cert-verify: true

proxy-groups:
  - name: Server
    type: select
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - v27.tiktokcdn.com
      - investor.medallia.com
      - investor.spotify.com
      - api2-t3.musical.ly
      - api-t3.tiktokv.com
      - video.joox.com
      - www.spotify.com
      - tiktokcdn.com.c.worldfcdn.com
      - tiktokv.com.c.worldfcdn2.com
      - ttlivecdn.com.c.worldfcdn.com

rules:
 - MATCH,Server
